apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluestar-th
  namespace: bluestar-th
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bluestar.th.reeldev.jp
      secretName: bluestar-th-tls   # cert-manager が自動生成 or 手動で作成
  rules:
    - host: bluestar.th.reeldev.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bluestar-th
                port:
                  number: 80
